/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Agent_window (void);
GtkWidget* create_ajouter_hotel_window (void);
GtkWidget* create_ajouter_vol_window (void);
GtkWidget* create_edit_hotel (void);
GtkWidget* create_edit_vol_window (void);
