/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Agent_window (void)
{
  GtkWidget *Agent_window;
  GtkWidget *fixed2;
  GtkWidget *disconnect_agent_button;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image35;
  GtkWidget *label152;
  GtkWidget *label531;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport2;
  GtkWidget *notebook2;
  GtkWidget *fixed15;
  GtkWidget *treeview_hotel;
  GtkWidget *ajouter_nouveau_med;
  GtkWidget *alignment38;
  GtkWidget *hbox38;
  GtkWidget *image54;
  GtkWidget *label196;
  GtkWidget *search_hotel;
  GtkWidget *alignment48;
  GtkWidget *hbox48;
  GtkWidget *image64;
  GtkWidget *label248;
  GtkWidget *refresh_hotel;
  GtkWidget *alignment49;
  GtkWidget *hbox49;
  GtkWidget *image65;
  GtkWidget *label249;
  GtkWidget *hotel_label;
  GtkWidget *fixed7;
  GtkWidget *treeview_vol;
  GtkWidget *refresh_vol;
  GtkWidget *alignment50;
  GtkWidget *hbox50;
  GtkWidget *image66;
  GtkWidget *label250;
  GtkWidget *ajouter_nouveau_vol;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image53;
  GtkWidget *label195;
  GtkWidget *search_vol;
  GtkWidget *alignment55;
  GtkWidget *hbox55;
  GtkWidget *image71;
  GtkWidget *label255;
  GtkWidget *vol_label;
  GtkWidget *Sections;

  Agent_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Agent_window), _("Espace Agent"));
  gtk_window_set_resizable (GTK_WINDOW (Agent_window), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Agent_window), fixed2);
  gtk_widget_set_size_request (fixed2, 900, 650);

  disconnect_agent_button = gtk_button_new ();
  gtk_widget_show (disconnect_agent_button);
  gtk_fixed_put (GTK_FIXED (fixed2), disconnect_agent_button, 744, 16);
  gtk_widget_set_size_request (disconnect_agent_button, 120, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (disconnect_agent_button), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image35 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox23), image35, FALSE, FALSE, 0);

  label152 = gtk_label_new_with_mnemonic (_("D\303\251connecter"));
  gtk_widget_show (label152);
  gtk_box_pack_start (GTK_BOX (hbox23), label152, FALSE, FALSE, 0);

  label531 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" size=\"xx-large\"><b><i> Espace Agent</i></b></span>"));
  gtk_widget_show (label531);
  gtk_fixed_put (GTK_FIXED (fixed2), label531, 40, 8);
  gtk_widget_set_size_request (label531, 376, 32);
  gtk_label_set_use_markup (GTK_LABEL (label531), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 40);
  gtk_widget_set_size_request (notebook1, 800, 568);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (viewport1), scrolledwindow2);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport2);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (viewport2), notebook2);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook2), GTK_POS_LEFT);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed15);

  treeview_hotel = gtk_tree_view_new ();
  gtk_widget_show (treeview_hotel);
  gtk_fixed_put (GTK_FIXED (fixed15), treeview_hotel, 0, 112);
  gtk_widget_set_size_request (treeview_hotel, 680, 272);

  ajouter_nouveau_med = gtk_button_new ();
  gtk_widget_show (ajouter_nouveau_med);
  gtk_fixed_put (GTK_FIXED (fixed15), ajouter_nouveau_med, 16, 24);
  gtk_widget_set_size_request (ajouter_nouveau_med, 104, 32);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (ajouter_nouveau_med), alignment38);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox38);

  image54 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox38), image54, FALSE, FALSE, 0);

  label196 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label196);
  gtk_box_pack_start (GTK_BOX (hbox38), label196, FALSE, FALSE, 0);

  search_hotel = gtk_button_new ();
  gtk_widget_show (search_hotel);
  gtk_fixed_put (GTK_FIXED (fixed15), search_hotel, 477, 24);
  gtk_widget_set_size_request (search_hotel, 91, 32);

  alignment48 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment48);
  gtk_container_add (GTK_CONTAINER (search_hotel), alignment48);

  hbox48 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox48);
  gtk_container_add (GTK_CONTAINER (alignment48), hbox48);

  image64 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox48), image64, FALSE, FALSE, 0);

  label248 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label248);
  gtk_box_pack_start (GTK_BOX (hbox48), label248, FALSE, FALSE, 0);

  refresh_hotel = gtk_button_new ();
  gtk_widget_show (refresh_hotel);
  gtk_fixed_put (GTK_FIXED (fixed15), refresh_hotel, 575, 24);
  gtk_widget_set_size_request (refresh_hotel, 102, 32);

  alignment49 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment49);
  gtk_container_add (GTK_CONTAINER (refresh_hotel), alignment49);

  hbox49 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox49);
  gtk_container_add (GTK_CONTAINER (alignment49), hbox49);

  image65 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox49), image65, FALSE, FALSE, 0);

  label249 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label249);
  gtk_box_pack_start (GTK_BOX (hbox49), label249, FALSE, FALSE, 0);

  hotel_label = gtk_label_new (_("Hotel"));
  gtk_widget_show (hotel_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), hotel_label);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed7);

  treeview_vol = gtk_tree_view_new ();
  gtk_widget_show (treeview_vol);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview_vol, 0, 112);
  gtk_widget_set_size_request (treeview_vol, 680, 384);

  refresh_vol = gtk_button_new ();
  gtk_widget_show (refresh_vol);
  gtk_fixed_put (GTK_FIXED (fixed7), refresh_vol, 575, 24);
  gtk_widget_set_size_request (refresh_vol, 102, 32);

  alignment50 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment50);
  gtk_container_add (GTK_CONTAINER (refresh_vol), alignment50);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment50), hbox50);

  image66 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox50), image66, FALSE, FALSE, 0);

  label250 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label250);
  gtk_box_pack_start (GTK_BOX (hbox50), label250, FALSE, FALSE, 0);

  ajouter_nouveau_vol = gtk_button_new ();
  gtk_widget_show (ajouter_nouveau_vol);
  gtk_fixed_put (GTK_FIXED (fixed7), ajouter_nouveau_vol, 16, 24);
  gtk_widget_set_size_request (ajouter_nouveau_vol, 104, 32);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (ajouter_nouveau_vol), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image53 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox37), image53, FALSE, FALSE, 0);

  label195 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label195);
  gtk_box_pack_start (GTK_BOX (hbox37), label195, FALSE, FALSE, 0);

  search_vol = gtk_button_new ();
  gtk_widget_show (search_vol);
  gtk_fixed_put (GTK_FIXED (fixed7), search_vol, 477, 24);
  gtk_widget_set_size_request (search_vol, 91, 32);

  alignment55 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment55);
  gtk_container_add (GTK_CONTAINER (search_vol), alignment55);

  hbox55 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox55);
  gtk_container_add (GTK_CONTAINER (alignment55), hbox55);

  image71 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image71);
  gtk_box_pack_start (GTK_BOX (hbox55), image71, FALSE, FALSE, 0);

  label255 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label255);
  gtk_box_pack_start (GTK_BOX (hbox55), label255, FALSE, FALSE, 0);

  vol_label = gtk_label_new (_("Vol"));
  gtk_widget_show (vol_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), vol_label);

  Sections = gtk_label_new (_("Sections"));
  gtk_widget_show (Sections);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Sections);

  g_signal_connect ((gpointer) Agent_window, "show",
                    G_CALLBACK (on_Agent_window_show),
                    NULL);
  g_signal_connect ((gpointer) disconnect_agent_button, "clicked",
                    G_CALLBACK (on_quit_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_nouveau_med, "clicked",
                    G_CALLBACK (on_ajouter_nouveau_hotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) search_hotel, "clicked",
                    G_CALLBACK (on_search_hotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_hotel, "clicked",
                    G_CALLBACK (on_refresh_hotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_vol, "clicked",
                    G_CALLBACK (on_refresh_vol_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_nouveau_vol, "clicked",
                    G_CALLBACK (on_ajouter_nouveau_vol_clicked),
                    NULL);
  g_signal_connect ((gpointer) search_vol, "clicked",
                    G_CALLBACK (on_search_vol_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Agent_window, Agent_window, "Agent_window");
  GLADE_HOOKUP_OBJECT (Agent_window, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Agent_window, disconnect_agent_button, "disconnect_agent_button");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Agent_window, image35, "image35");
  GLADE_HOOKUP_OBJECT (Agent_window, label152, "label152");
  GLADE_HOOKUP_OBJECT (Agent_window, label531, "label531");
  GLADE_HOOKUP_OBJECT (Agent_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Agent_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Agent_window, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (Agent_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (Agent_window, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (Agent_window, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (Agent_window, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Agent_window, treeview_hotel, "treeview_hotel");
  GLADE_HOOKUP_OBJECT (Agent_window, ajouter_nouveau_med, "ajouter_nouveau_med");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (Agent_window, image54, "image54");
  GLADE_HOOKUP_OBJECT (Agent_window, label196, "label196");
  GLADE_HOOKUP_OBJECT (Agent_window, search_hotel, "search_hotel");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment48, "alignment48");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (Agent_window, image64, "image64");
  GLADE_HOOKUP_OBJECT (Agent_window, label248, "label248");
  GLADE_HOOKUP_OBJECT (Agent_window, refresh_hotel, "refresh_hotel");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment49, "alignment49");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (Agent_window, image65, "image65");
  GLADE_HOOKUP_OBJECT (Agent_window, label249, "label249");
  GLADE_HOOKUP_OBJECT (Agent_window, hotel_label, "hotel_label");
  GLADE_HOOKUP_OBJECT (Agent_window, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Agent_window, treeview_vol, "treeview_vol");
  GLADE_HOOKUP_OBJECT (Agent_window, refresh_vol, "refresh_vol");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment50, "alignment50");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (Agent_window, image66, "image66");
  GLADE_HOOKUP_OBJECT (Agent_window, label250, "label250");
  GLADE_HOOKUP_OBJECT (Agent_window, ajouter_nouveau_vol, "ajouter_nouveau_vol");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (Agent_window, image53, "image53");
  GLADE_HOOKUP_OBJECT (Agent_window, label195, "label195");
  GLADE_HOOKUP_OBJECT (Agent_window, search_vol, "search_vol");
  GLADE_HOOKUP_OBJECT (Agent_window, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (Agent_window, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (Agent_window, image71, "image71");
  GLADE_HOOKUP_OBJECT (Agent_window, label255, "label255");
  GLADE_HOOKUP_OBJECT (Agent_window, vol_label, "vol_label");
  GLADE_HOOKUP_OBJECT (Agent_window, Sections, "Sections");

  return Agent_window;
}

GtkWidget*
create_ajouter_hotel_window (void)
{
  GtkWidget *ajouter_hotel_window;
  GtkWidget *fixed17;
  GtkWidget *adresse_hotel;
  GtkWidget *email_hotel;
  GtkWidget *numero_hotel;
  GtkWidget *nom_hotel;
  GtkWidget *nombre_chambre;
  GtkWidget *label104;
  GtkWidget *label111;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label197;
  GtkWidget *mail_hotel_combobox;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label563;
  GtkWidget *ajouter_hotel;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image24;
  GtkWidget *label113;
  GtkWidget *annuler_hotel;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image40;
  GtkWidget *label171;
  GtkWidget *label_verif_hotel_info;
  GtkWidget *classement_hotel;

  ajouter_hotel_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_hotel_window), _("Ajouter nouveau Hotel"));
  gtk_window_set_resizable (GTK_WINDOW (ajouter_hotel_window), FALSE);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (ajouter_hotel_window), fixed17);
  gtk_widget_set_size_request (fixed17, 620, 520);

  adresse_hotel = gtk_entry_new ();
  gtk_widget_show (adresse_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), adresse_hotel, 192, 288);
  gtk_widget_set_size_request (adresse_hotel, 270, 27);
  gtk_entry_set_max_length (GTK_ENTRY (adresse_hotel), 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse_hotel), 8226);

  email_hotel = gtk_entry_new ();
  gtk_widget_show (email_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), email_hotel, 192, 168);
  gtk_widget_set_size_request (email_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_hotel), 8226);

  numero_hotel = gtk_entry_new ();
  gtk_widget_show (numero_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), numero_hotel, 192, 224);
  gtk_widget_set_size_request (numero_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (numero_hotel), 8226);

  nom_hotel = gtk_entry_new ();
  gtk_widget_show (nom_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), nom_hotel, 192, 24);
  gtk_widget_set_size_request (nom_hotel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_hotel), 8226);

  nombre_chambre = gtk_entry_new ();
  gtk_widget_show (nombre_chambre);
  gtk_fixed_put (GTK_FIXED (fixed17), nombre_chambre, 192, 120);
  gtk_widget_set_size_request (nombre_chambre, 45, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nombre_chambre), 8226);

  label104 = gtk_label_new (_("Classement  :"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed17), label104, 24, 72);
  gtk_widget_set_size_request (label104, 96, 32);

  label111 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed17), label111, 16, 24);
  gtk_widget_set_size_request (label111, 72, 32);

  label105 = gtk_label_new (_("Nombre de chambre :"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed17), label105, 8, 120);
  gtk_widget_set_size_request (label105, 172, 27);

  label106 = gtk_label_new (_("E-mail :"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed17), label106, 20, 168);
  gtk_widget_set_size_request (label106, 72, 32);

  label197 = gtk_label_new (_("@"));
  gtk_widget_show (label197);
  gtk_fixed_put (GTK_FIXED (fixed17), label197, 352, 168);
  gtk_widget_set_size_request (label197, 32, 24);

  mail_hotel_combobox = gtk_combo_box_new_text ();
  gtk_widget_show (mail_hotel_combobox);
  gtk_fixed_put (GTK_FIXED (fixed17), mail_hotel_combobox, 376, 168);
  gtk_widget_set_size_request (mail_hotel_combobox, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("gmail.com"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("yahoo.com"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("icloud.com"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("yandex.ru"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("outlook.com"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("hotmail.com"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mail_hotel_combobox), _("esprit.tn"));

  label109 = gtk_label_new (_("Num\303\251ro de t\303\251lephone :"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed17), label109, 8, 224);
  gtk_widget_set_size_request (label109, 172, 32);

  label110 = gtk_label_new (_("Adresse : "));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed17), label110, 24, 288);
  gtk_widget_set_size_request (label110, 88, 32);

  label563 = gtk_label_new (_("\303\251toiles"));
  gtk_widget_show (label563);
  gtk_fixed_put (GTK_FIXED (fixed17), label563, 256, 80);
  gtk_widget_set_size_request (label563, 57, 17);

  ajouter_hotel = gtk_button_new ();
  gtk_widget_show (ajouter_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), ajouter_hotel, 344, 432);
  gtk_widget_set_size_request (ajouter_hotel, 105, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (ajouter_hotel), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image24 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox16), image24, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox16), label113, FALSE, FALSE, 0);

  annuler_hotel = gtk_button_new ();
  gtk_widget_show (annuler_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), annuler_hotel, 456, 432);
  gtk_widget_set_size_request (annuler_hotel, 105, 29);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (annuler_hotel), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image40 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox27), image40, FALSE, FALSE, 0);

  label171 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label171);
  gtk_box_pack_start (GTK_BOX (hbox27), label171, FALSE, FALSE, 0);

  label_verif_hotel_info = gtk_label_new ("");
  gtk_widget_show (label_verif_hotel_info);
  gtk_fixed_put (GTK_FIXED (fixed17), label_verif_hotel_info, 128, 352);
  gtk_widget_set_size_request (label_verif_hotel_info, 349, 49);

  classement_hotel = gtk_combo_box_new_text ();
  gtk_widget_show (classement_hotel);
  gtk_fixed_put (GTK_FIXED (fixed17), classement_hotel, 192, 72);
  gtk_widget_set_size_request (classement_hotel, 50, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (classement_hotel), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classement_hotel), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classement_hotel), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classement_hotel), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classement_hotel), _("5"));

  g_signal_connect ((gpointer) ajouter_hotel, "clicked",
                    G_CALLBACK (on_ajouter_hotel_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_hotel, "clicked",
                    G_CALLBACK (on_annuler_hotel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_hotel_window, ajouter_hotel_window, "ajouter_hotel_window");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, adresse_hotel, "adresse_hotel");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, email_hotel, "email_hotel");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, numero_hotel, "numero_hotel");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, nom_hotel, "nom_hotel");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, nombre_chambre, "nombre_chambre");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label104, "label104");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label111, "label111");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label105, "label105");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label106, "label106");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label197, "label197");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, mail_hotel_combobox, "mail_hotel_combobox");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label109, "label109");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label110, "label110");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label563, "label563");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, ajouter_hotel, "ajouter_hotel");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, image24, "image24");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label113, "label113");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, annuler_hotel, "annuler_hotel");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, image40, "image40");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label171, "label171");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, label_verif_hotel_info, "label_verif_hotel_info");
  GLADE_HOOKUP_OBJECT (ajouter_hotel_window, classement_hotel, "classement_hotel");

  return ajouter_hotel_window;
}

GtkWidget*
create_ajouter_vol_window (void)
{
  GtkWidget *ajouter_vol_window;
  GtkWidget *fixed18;
  GtkWidget *label_verif_tec_info;
  GtkWidget *fixed38;
  GtkWidget *destination_vol;
  GtkWidget *nom_vol;
  GtkWidget *ville_depart;
  GtkWidget *label204;
  GtkWidget *label201;
  GtkWidget *label200;
  GtkWidget *label202;
  GtkWidget *ajouter_vol;
  GtkWidget *alignment39;
  GtkWidget *hbox39;
  GtkWidget *image55;
  GtkWidget *label198;
  GtkWidget *annuler_vol;
  GtkWidget *alignment40;
  GtkWidget *hbox40;
  GtkWidget *image56;
  GtkWidget *label199;
  GtkObject *jour_vol_adj;
  GtkWidget *jour_vol;
  GtkObject *mois_vol_adj;
  GtkWidget *mois_vol;
  GtkObject *annee_vol_adj;
  GtkWidget *annee_vol;
  GtkWidget *label_verif_vol;

  ajouter_vol_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_vol_window), _("Ajouter nouveau vol"));
  gtk_window_set_resizable (GTK_WINDOW (ajouter_vol_window), FALSE);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (ajouter_vol_window), fixed18);
  gtk_widget_set_size_request (fixed18, 620, 520);

  label_verif_tec_info = gtk_label_new ("");
  gtk_widget_show (label_verif_tec_info);
  gtk_fixed_put (GTK_FIXED (fixed18), label_verif_tec_info, 128, 384);
  gtk_widget_set_size_request (label_verif_tec_info, 349, 49);

  fixed38 = gtk_fixed_new ();
  gtk_widget_show (fixed38);
  gtk_fixed_put (GTK_FIXED (fixed18), fixed38, 0, 0);
  gtk_widget_set_size_request (fixed38, 624, 536);

  destination_vol = gtk_entry_new ();
  gtk_widget_show (destination_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), destination_vol, 192, 72);
  gtk_widget_set_size_request (destination_vol, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (destination_vol), 8226);

  nom_vol = gtk_entry_new ();
  gtk_widget_show (nom_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), nom_vol, 192, 24);
  gtk_widget_set_size_request (nom_vol, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_vol), 8226);

  ville_depart = gtk_entry_new ();
  gtk_widget_show (ville_depart);
  gtk_fixed_put (GTK_FIXED (fixed38), ville_depart, 192, 176);
  gtk_widget_set_size_request (ville_depart, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ville_depart), 8226);

  label204 = gtk_label_new (_("Ville de depart :"));
  gtk_widget_show (label204);
  gtk_fixed_put (GTK_FIXED (fixed38), label204, 16, 176);
  gtk_widget_set_size_request (label204, 139, 32);

  label201 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed38), label201, 16, 24);
  gtk_widget_set_size_request (label201, 72, 32);

  label200 = gtk_label_new (_("Destination :"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed38), label200, 24, 72);
  gtk_widget_set_size_request (label200, 96, 32);

  label202 = gtk_label_new (_("Date de depart :"));
  gtk_widget_show (label202);
  gtk_fixed_put (GTK_FIXED (fixed38), label202, 8, 120);
  gtk_widget_set_size_request (label202, 152, 32);

  ajouter_vol = gtk_button_new ();
  gtk_widget_show (ajouter_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), ajouter_vol, 328, 360);
  gtk_widget_set_size_request (ajouter_vol, 105, 29);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (ajouter_vol), alignment39);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox39);

  image55 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox39), image55, FALSE, FALSE, 0);

  label198 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label198);
  gtk_box_pack_start (GTK_BOX (hbox39), label198, FALSE, FALSE, 0);

  annuler_vol = gtk_button_new ();
  gtk_widget_show (annuler_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), annuler_vol, 464, 360);
  gtk_widget_set_size_request (annuler_vol, 105, 29);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (annuler_vol), alignment40);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox40);

  image56 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox40), image56, FALSE, FALSE, 0);

  label199 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label199);
  gtk_box_pack_start (GTK_BOX (hbox40), label199, FALSE, FALSE, 0);

  jour_vol_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  jour_vol = gtk_spin_button_new (GTK_ADJUSTMENT (jour_vol_adj), 1, 0);
  gtk_widget_show (jour_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), jour_vol, 184, 120);
  gtk_widget_set_size_request (jour_vol, 60, 27);

  mois_vol_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_vol = gtk_spin_button_new (GTK_ADJUSTMENT (mois_vol_adj), 1, 0);
  gtk_widget_show (mois_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), mois_vol, 256, 120);
  gtk_widget_set_size_request (mois_vol, 60, 27);

  annee_vol_adj = gtk_adjustment_new (2019, 2019, 2019, 1, 10, 10);
  annee_vol = gtk_spin_button_new (GTK_ADJUSTMENT (annee_vol_adj), 1, 0);
  gtk_widget_show (annee_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), annee_vol, 328, 120);
  gtk_widget_set_size_request (annee_vol, 60, 27);

  label_verif_vol = gtk_label_new ("");
  gtk_widget_show (label_verif_vol);
  gtk_fixed_put (GTK_FIXED (fixed38), label_verif_vol, 144, 272);
  gtk_widget_set_size_request (label_verif_vol, 349, 49);

  g_signal_connect ((gpointer) ajouter_vol, "clicked",
                    G_CALLBACK (on_ajouter_vol_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_vol, "clicked",
                    G_CALLBACK (on_annuler_vol_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_vol_window, ajouter_vol_window, "ajouter_vol_window");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label_verif_tec_info, "label_verif_tec_info");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, fixed38, "fixed38");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, destination_vol, "destination_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, nom_vol, "nom_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, ville_depart, "ville_depart");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label204, "label204");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label201, "label201");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label200, "label200");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label202, "label202");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, ajouter_vol, "ajouter_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, image55, "image55");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label198, "label198");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, annuler_vol, "annuler_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, image56, "image56");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label199, "label199");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, jour_vol, "jour_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, mois_vol, "mois_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, annee_vol, "annee_vol");
  GLADE_HOOKUP_OBJECT (ajouter_vol_window, label_verif_vol, "label_verif_vol");

  return ajouter_vol_window;
}

GtkWidget*
create_edit_hotel (void)
{
  GtkWidget *edit_hotel;
  GtkWidget *fixed31;
  GtkWidget *id_search;
  GtkWidget *nom_input;
  GtkWidget *numero_input;
  GtkWidget *adresse_rue;
  GtkWidget *label164;
  GtkWidget *edit_nombre_entry;
  GtkWidget *label564;
  GtkWidget *label154;
  GtkWidget *label156;
  GtkWidget *label160;
  GtkWidget *label161;
  GtkWidget *label165;
  GtkWidget *label157;
  GtkWidget *supprimer_id;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image39;
  GtkWidget *label163;
  GtkWidget *edit_button;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image38;
  GtkWidget *label162;
  GtkWidget *edit_classement_combobox;
  GtkWidget *label_not_found;
  GtkWidget *button_trouver;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image36;
  GtkWidget *label155;

  edit_hotel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (edit_hotel), _("Modifier hotel"));
  gtk_window_set_resizable (GTK_WINDOW (edit_hotel), FALSE);

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (edit_hotel), fixed31);
  gtk_widget_set_size_request (fixed31, 540, 600);

  id_search = gtk_entry_new ();
  gtk_widget_show (id_search);
  gtk_fixed_put (GTK_FIXED (fixed31), id_search, 200, 56);
  gtk_widget_set_size_request (id_search, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_search), 8226);

  nom_input = gtk_entry_new ();
  gtk_widget_show (nom_input);
  gtk_fixed_put (GTK_FIXED (fixed31), nom_input, 200, 160);
  gtk_widget_set_size_request (nom_input, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_input), 8226);

  numero_input = gtk_entry_new ();
  gtk_widget_show (numero_input);
  gtk_fixed_put (GTK_FIXED (fixed31), numero_input, 200, 328);
  gtk_widget_set_size_request (numero_input, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (numero_input), 8226);

  adresse_rue = gtk_entry_new ();
  gtk_widget_show (adresse_rue);
  gtk_fixed_put (GTK_FIXED (fixed31), adresse_rue, 200, 400);
  gtk_widget_set_size_request (adresse_rue, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse_rue), 8226);

  label164 = gtk_label_new ("");
  gtk_widget_show (label164);
  gtk_fixed_put (GTK_FIXED (fixed31), label164, 120, 552);
  gtk_widget_set_size_request (label164, 304, 40);

  edit_nombre_entry = gtk_entry_new ();
  gtk_widget_show (edit_nombre_entry);
  gtk_fixed_put (GTK_FIXED (fixed31), edit_nombre_entry, 200, 216);
  gtk_widget_set_size_request (edit_nombre_entry, 45, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (edit_nombre_entry), 8226);

  label564 = gtk_label_new (_("\303\251toiles"));
  gtk_widget_show (label564);
  gtk_fixed_put (GTK_FIXED (fixed31), label564, 264, 272);
  gtk_widget_set_size_request (label564, 57, 17);

  label154 = gtk_label_new (_("Entrez l'identifiant: "));
  gtk_widget_show (label154);
  gtk_fixed_put (GTK_FIXED (fixed31), label154, 48, 64);
  gtk_widget_set_size_request (label154, 152, 24);

  label156 = gtk_label_new (_("Nom"));
  gtk_widget_show (label156);
  gtk_fixed_put (GTK_FIXED (fixed31), label156, 33, 160);
  gtk_widget_set_size_request (label156, 96, 24);

  label160 = gtk_label_new (_("Classement"));
  gtk_widget_show (label160);
  gtk_fixed_put (GTK_FIXED (fixed31), label160, 16, 264);
  gtk_widget_set_size_request (label160, 152, 32);

  label161 = gtk_label_new (_("Num\303\251ro"));
  gtk_widget_show (label161);
  gtk_fixed_put (GTK_FIXED (fixed31), label161, 48, 320);
  gtk_widget_set_size_request (label161, 96, 40);

  label165 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label165);
  gtk_fixed_put (GTK_FIXED (fixed31), label165, 56, 400);
  gtk_widget_set_size_request (label165, 80, 24);

  label157 = gtk_label_new (_("Nombre de chambre"));
  gtk_widget_show (label157);
  gtk_fixed_put (GTK_FIXED (fixed31), label157, 24, 208);
  gtk_widget_set_size_request (label157, 152, 40);

  supprimer_id = gtk_button_new ();
  gtk_widget_show (supprimer_id);
  gtk_fixed_put (GTK_FIXED (fixed31), supprimer_id, 104, 500);
  gtk_widget_set_size_request (supprimer_id, 112, 48);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (supprimer_id), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image39 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox26), image39, FALSE, FALSE, 0);

  label163 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox26), label163, FALSE, FALSE, 0);

  edit_button = gtk_button_new ();
  gtk_widget_show (edit_button);
  gtk_fixed_put (GTK_FIXED (fixed31), edit_button, 328, 500);
  gtk_widget_set_size_request (edit_button, 112, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (edit_button), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image38 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox25), image38, FALSE, FALSE, 0);

  label162 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label162);
  gtk_box_pack_start (GTK_BOX (hbox25), label162, FALSE, FALSE, 0);

  edit_classement_combobox = gtk_combo_box_new_text ();
  gtk_widget_show (edit_classement_combobox);
  gtk_fixed_put (GTK_FIXED (fixed31), edit_classement_combobox, 200, 264);
  gtk_widget_set_size_request (edit_classement_combobox, 50, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_classement_combobox), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_classement_combobox), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_classement_combobox), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_classement_combobox), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_classement_combobox), _("5"));

  label_not_found = gtk_label_new ("");
  gtk_widget_show (label_not_found);
  gtk_fixed_put (GTK_FIXED (fixed31), label_not_found, 8, 32);
  gtk_widget_set_size_request (label_not_found, 472, 64);

  button_trouver = gtk_button_new ();
  gtk_widget_show (button_trouver);
  gtk_fixed_put (GTK_FIXED (fixed31), button_trouver, 312, 112);
  gtk_widget_set_size_request (button_trouver, 91, 32);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button_trouver), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image36 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox24), image36, FALSE, FALSE, 0);

  label155 = gtk_label_new_with_mnemonic (_("Trouver"));
  gtk_widget_show (label155);
  gtk_box_pack_start (GTK_BOX (hbox24), label155, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supprimer_id, "clicked",
                    G_CALLBACK (on_supprimer_id_clicked),
                    NULL);
  g_signal_connect ((gpointer) edit_button, "clicked",
                    G_CALLBACK (on_edit_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_trouver, "clicked",
                    G_CALLBACK (on_button_trouver_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (edit_hotel, edit_hotel, "edit_hotel");
  GLADE_HOOKUP_OBJECT (edit_hotel, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (edit_hotel, id_search, "id_search");
  GLADE_HOOKUP_OBJECT (edit_hotel, nom_input, "nom_input");
  GLADE_HOOKUP_OBJECT (edit_hotel, numero_input, "numero_input");
  GLADE_HOOKUP_OBJECT (edit_hotel, adresse_rue, "adresse_rue");
  GLADE_HOOKUP_OBJECT (edit_hotel, label164, "label164");
  GLADE_HOOKUP_OBJECT (edit_hotel, edit_nombre_entry, "edit_nombre_entry");
  GLADE_HOOKUP_OBJECT (edit_hotel, label564, "label564");
  GLADE_HOOKUP_OBJECT (edit_hotel, label154, "label154");
  GLADE_HOOKUP_OBJECT (edit_hotel, label156, "label156");
  GLADE_HOOKUP_OBJECT (edit_hotel, label160, "label160");
  GLADE_HOOKUP_OBJECT (edit_hotel, label161, "label161");
  GLADE_HOOKUP_OBJECT (edit_hotel, label165, "label165");
  GLADE_HOOKUP_OBJECT (edit_hotel, label157, "label157");
  GLADE_HOOKUP_OBJECT (edit_hotel, supprimer_id, "supprimer_id");
  GLADE_HOOKUP_OBJECT (edit_hotel, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (edit_hotel, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (edit_hotel, image39, "image39");
  GLADE_HOOKUP_OBJECT (edit_hotel, label163, "label163");
  GLADE_HOOKUP_OBJECT (edit_hotel, edit_button, "edit_button");
  GLADE_HOOKUP_OBJECT (edit_hotel, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (edit_hotel, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (edit_hotel, image38, "image38");
  GLADE_HOOKUP_OBJECT (edit_hotel, label162, "label162");
  GLADE_HOOKUP_OBJECT (edit_hotel, edit_classement_combobox, "edit_classement_combobox");
  GLADE_HOOKUP_OBJECT (edit_hotel, label_not_found, "label_not_found");
  GLADE_HOOKUP_OBJECT (edit_hotel, button_trouver, "button_trouver");
  GLADE_HOOKUP_OBJECT (edit_hotel, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (edit_hotel, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (edit_hotel, image36, "image36");
  GLADE_HOOKUP_OBJECT (edit_hotel, label155, "label155");

  return edit_hotel;
}

GtkWidget*
create_edit_vol_window (void)
{
  GtkWidget *edit_vol_window;
  GtkWidget *fixed49;
  GtkWidget *id_inf_search;
  GtkWidget *nom_inf;
  GtkWidget *destination_inf;
  GtkWidget *ville_depart_inf;
  GtkWidget *label276;
  GtkWidget *label270;
  GtkWidget *button_trouver_inf;
  GtkWidget *alignment60;
  GtkWidget *hbox60;
  GtkWidget *image76;
  GtkWidget *label264;
  GtkWidget *label271;
  GtkWidget *label266;
  GtkWidget *supprimer_id_inf;
  GtkWidget *alignment61;
  GtkWidget *hbox61;
  GtkWidget *image77;
  GtkWidget *label274;
  GtkWidget *edit_inf_button;
  GtkWidget *alignment62;
  GtkWidget *hbox62;
  GtkWidget *image78;
  GtkWidget *label275;
  GtkWidget *label265;
  GtkObject *jour_inf_adj;
  GtkWidget *jour_inf;
  GtkWidget *label268;
  GtkWidget *label269;
  GtkObject *mois_inf_adj;
  GtkWidget *mois_inf;
  GtkObject *annee_inf_adj;
  GtkWidget *annee_inf;

  edit_vol_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (edit_vol_window), _("Modifier Vol"));
  gtk_window_set_resizable (GTK_WINDOW (edit_vol_window), FALSE);

  fixed49 = gtk_fixed_new ();
  gtk_widget_show (fixed49);
  gtk_container_add (GTK_CONTAINER (edit_vol_window), fixed49);
  gtk_widget_set_size_request (fixed49, 540, 600);

  id_inf_search = gtk_entry_new ();
  gtk_widget_show (id_inf_search);
  gtk_fixed_put (GTK_FIXED (fixed49), id_inf_search, 200, 56);
  gtk_widget_set_size_request (id_inf_search, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_inf_search), 8226);

  nom_inf = gtk_entry_new ();
  gtk_widget_show (nom_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), nom_inf, 200, 160);
  gtk_widget_set_size_request (nom_inf, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_inf), 8226);

  destination_inf = gtk_entry_new ();
  gtk_widget_show (destination_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), destination_inf, 200, 210);
  gtk_widget_set_size_request (destination_inf, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (destination_inf), 8226);

  ville_depart_inf = gtk_entry_new ();
  gtk_widget_show (ville_depart_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), ville_depart_inf, 200, 264);
  gtk_widget_set_size_request (ville_depart_inf, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ville_depart_inf), 8226);

  label276 = gtk_label_new ("");
  gtk_widget_show (label276);
  gtk_fixed_put (GTK_FIXED (fixed49), label276, 40, 80);
  gtk_widget_set_size_request (label276, 472, 64);

  label270 = gtk_label_new (_("Entrez l'identifiant: "));
  gtk_widget_show (label270);
  gtk_fixed_put (GTK_FIXED (fixed49), label270, 48, 64);
  gtk_widget_set_size_request (label270, 152, 24);

  button_trouver_inf = gtk_button_new ();
  gtk_widget_show (button_trouver_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), button_trouver_inf, 384, 56);
  gtk_widget_set_size_request (button_trouver_inf, 91, 32);

  alignment60 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment60);
  gtk_container_add (GTK_CONTAINER (button_trouver_inf), alignment60);

  hbox60 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox60);
  gtk_container_add (GTK_CONTAINER (alignment60), hbox60);

  image76 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image76);
  gtk_box_pack_start (GTK_BOX (hbox60), image76, FALSE, FALSE, 0);

  label264 = gtk_label_new_with_mnemonic (_("Trouver"));
  gtk_widget_show (label264);
  gtk_box_pack_start (GTK_BOX (hbox60), label264, FALSE, FALSE, 0);

  label271 = gtk_label_new (_("Destination"));
  gtk_widget_show (label271);
  gtk_fixed_put (GTK_FIXED (fixed49), label271, 50, 210);
  gtk_widget_set_size_request (label271, 80, 24);

  label266 = gtk_label_new (_("Ville de depart"));
  gtk_widget_show (label266);
  gtk_fixed_put (GTK_FIXED (fixed49), label266, 48, 264);
  gtk_widget_set_size_request (label266, 112, 40);

  supprimer_id_inf = gtk_button_new ();
  gtk_widget_show (supprimer_id_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), supprimer_id_inf, 104, 500);
  gtk_widget_set_size_request (supprimer_id_inf, 112, 48);

  alignment61 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment61);
  gtk_container_add (GTK_CONTAINER (supprimer_id_inf), alignment61);

  hbox61 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox61);
  gtk_container_add (GTK_CONTAINER (alignment61), hbox61);

  image77 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image77);
  gtk_box_pack_start (GTK_BOX (hbox61), image77, FALSE, FALSE, 0);

  label274 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label274);
  gtk_box_pack_start (GTK_BOX (hbox61), label274, FALSE, FALSE, 0);

  edit_inf_button = gtk_button_new ();
  gtk_widget_show (edit_inf_button);
  gtk_fixed_put (GTK_FIXED (fixed49), edit_inf_button, 328, 500);
  gtk_widget_set_size_request (edit_inf_button, 112, 48);

  alignment62 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment62);
  gtk_container_add (GTK_CONTAINER (edit_inf_button), alignment62);

  hbox62 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox62);
  gtk_container_add (GTK_CONTAINER (alignment62), hbox62);

  image78 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image78);
  gtk_box_pack_start (GTK_BOX (hbox62), image78, FALSE, FALSE, 0);

  label275 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label275);
  gtk_box_pack_start (GTK_BOX (hbox62), label275, FALSE, FALSE, 0);

  label265 = gtk_label_new (_("Nom"));
  gtk_widget_show (label265);
  gtk_fixed_put (GTK_FIXED (fixed49), label265, 33, 160);
  gtk_widget_set_size_request (label265, 96, 24);

  jour_inf_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_inf = gtk_spin_button_new (GTK_ADJUSTMENT (jour_inf_adj), 1, 0);
  gtk_widget_show (jour_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), jour_inf, 192, 336);
  gtk_widget_set_size_request (jour_inf, 60, 27);

  label268 = gtk_label_new (_("Date de depart"));
  gtk_widget_show (label268);
  gtk_fixed_put (GTK_FIXED (fixed49), label268, 24, 336);
  gtk_widget_set_size_request (label268, 152, 32);

  label269 = gtk_label_new ("");
  gtk_widget_show (label269);
  gtk_fixed_put (GTK_FIXED (fixed49), label269, 120, 552);
  gtk_widget_set_size_request (label269, 304, 40);

  mois_inf_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_inf = gtk_spin_button_new (GTK_ADJUSTMENT (mois_inf_adj), 1, 0);
  gtk_widget_show (mois_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), mois_inf, 280, 336);
  gtk_widget_set_size_request (mois_inf, 60, 27);

  annee_inf_adj = gtk_adjustment_new (2019, 2019, 2019, 1, 10, 10);
  annee_inf = gtk_spin_button_new (GTK_ADJUSTMENT (annee_inf_adj), 1, 0);
  gtk_widget_show (annee_inf);
  gtk_fixed_put (GTK_FIXED (fixed49), annee_inf, 368, 336);
  gtk_widget_set_size_request (annee_inf, 60, 27);

  g_signal_connect ((gpointer) button_trouver_inf, "clicked",
                    G_CALLBACK (on_button_trouver_inf_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_id_inf, "clicked",
                    G_CALLBACK (on_supprimer_id_inf_clicked),
                    NULL);
  g_signal_connect ((gpointer) edit_inf_button, "clicked",
                    G_CALLBACK (on_edit_inf_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (edit_vol_window, edit_vol_window, "edit_vol_window");
  GLADE_HOOKUP_OBJECT (edit_vol_window, fixed49, "fixed49");
  GLADE_HOOKUP_OBJECT (edit_vol_window, id_inf_search, "id_inf_search");
  GLADE_HOOKUP_OBJECT (edit_vol_window, nom_inf, "nom_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, destination_inf, "destination_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, ville_depart_inf, "ville_depart_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label276, "label276");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label270, "label270");
  GLADE_HOOKUP_OBJECT (edit_vol_window, button_trouver_inf, "button_trouver_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, alignment60, "alignment60");
  GLADE_HOOKUP_OBJECT (edit_vol_window, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (edit_vol_window, image76, "image76");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label264, "label264");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label271, "label271");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label266, "label266");
  GLADE_HOOKUP_OBJECT (edit_vol_window, supprimer_id_inf, "supprimer_id_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, alignment61, "alignment61");
  GLADE_HOOKUP_OBJECT (edit_vol_window, hbox61, "hbox61");
  GLADE_HOOKUP_OBJECT (edit_vol_window, image77, "image77");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label274, "label274");
  GLADE_HOOKUP_OBJECT (edit_vol_window, edit_inf_button, "edit_inf_button");
  GLADE_HOOKUP_OBJECT (edit_vol_window, alignment62, "alignment62");
  GLADE_HOOKUP_OBJECT (edit_vol_window, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (edit_vol_window, image78, "image78");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label275, "label275");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label265, "label265");
  GLADE_HOOKUP_OBJECT (edit_vol_window, jour_inf, "jour_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label268, "label268");
  GLADE_HOOKUP_OBJECT (edit_vol_window, label269, "label269");
  GLADE_HOOKUP_OBJECT (edit_vol_window, mois_inf, "mois_inf");
  GLADE_HOOKUP_OBJECT (edit_vol_window, annee_inf, "annee_inf");

  return edit_vol_window;
}

