/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Agent_window;
  GtkWidget *ajouter_hotel_window;
  GtkWidget *ajouter_vol_window;
  GtkWidget *edit_hotel;
  GtkWidget *edit_vol_window;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Agent_window = create_Agent_window ();
  gtk_widget_show (Agent_window);
  ajouter_hotel_window = create_ajouter_hotel_window ();
  gtk_widget_show (ajouter_hotel_window);
  ajouter_vol_window = create_ajouter_vol_window ();
  gtk_widget_show (ajouter_vol_window);
  edit_hotel = create_edit_hotel ();
  gtk_widget_show (edit_hotel);
  edit_vol_window = create_edit_vol_window ();
  gtk_widget_show (edit_vol_window);

  gtk_main ();
  return 0;
}

